# Generated by Django 5.2.9 on 2026-01-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='call_price',
            field=models.IntegerField(default=0),
        ),
    ]
