# Generated by Django 5.2.9 on 2026-01-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_is_banned_profile_reports_received_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='female_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='male_votes',
            field=models.IntegerField(default=0),
        ),
    ]
