# Generated by Django 5.2.9 on 2026-01-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0002_callrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('connected', 'Connected')], default='pending', max_length=10),
        ),
    ]
